export const girosSII = [
  // AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA
  { codigo: "011101", nombre: "CULTIVO DE TRIGO" },
  { codigo: "011102", nombre: "CULTIVO DE MAÍZ" },
  { codigo: "011103", nombre: "CULTIVO DE AVENA" },
  { codigo: "011104", nombre: "CULTIVO DE CEBADA" },
  {
    codigo: "011105",
    nombre: "CULTIVO DE OTROS CEREALES (EXCEPTO TRIGO, MAÍZ, AVENA Y CEBADA)",
  },
  { codigo: "011106", nombre: "CULTIVO DE POROTOS" },
  { codigo: "011107", nombre: "CULTIVO DE LUPINO" },
  {
    codigo: "011108",
    nombre: "CULTIVO DE OTRAS LEGUMBRES (EXCEPTO POROTOS Y LUPINO)",
  },
  { codigo: "011109", nombre: "CULTIVO DE SEMILLAS DE RAPS" },
  { codigo: "011110", nombre: "CULTIVO DE SEMILLAS DE MARAVILLA (GIRASOL)" },
  {
    codigo: "011111",
    nombre:
      "CULTIVO DE SEMILLAS DE CEREALES, LEGUMBRES Y OLEAGINOSAS (EXCEPTO SEMILLAS DE RAPS Y MARAVILLA)",
  },
  { codigo: "011200", nombre: "CULTIVO DE ARROZ" },
  { codigo: "011301", nombre: "CULTIVO DE PAPAS" },
  { codigo: "011302", nombre: "CULTIVO DE CAMOTES" },
  {
    codigo: "011303",
    nombre: "CULTIVO DE OTROS TUBÉRCULOS (EXCEPTO PAPAS Y CAMOTES)",
  },
  { codigo: "011304", nombre: "CULTIVO DE REMOLACHA AZUCARERA" },
  { codigo: "011305", nombre: "CULTIVO DE SEMILLAS DE HORTALIZAS" },
  { codigo: "011306", nombre: "CULTIVO DE HORTALIZAS Y MELONES" },
  { codigo: "011400", nombre: "CULTIVO DE CAÑA DE AZÚCAR" },
  { codigo: "011500", nombre: "CULTIVO DE TABACO" },
  { codigo: "011600", nombre: "CULTIVO DE PLANTAS DE FIBRA" },
  { codigo: "011901", nombre: "CULTIVO DE FLORES" },
  {
    codigo: "011902",
    nombre:
      "CULTIVOS FORRAJEROS EN PRADERAS MEJORADAS O SEMBRADAS; CULTIVOS SUPLEMENTARIOS FORRAJEROS",
  },
  {
    codigo: "011903",
    nombre:
      "CULTIVOS DE SEMILLAS DE FLORES; CULTIVO DE SEMILLAS DE PLANTAS FORRAJERAS",
  },
  {
    codigo: "012111",
    nombre: "CULTIVO DE UVA DESTINADA A LA PRODUCCIÓN DE PISCO Y AGUARDIENTE",
  },
  {
    codigo: "012112",
    nombre: "CULTIVO DE UVA DESTINADA A LA PRODUCCIÓN DE VINO",
  },
  { codigo: "012120", nombre: "CULTIVO DE UVA PARA MESA" },
  {
    codigo: "012200",
    nombre:
      "CULTIVO DE FRUTAS TROPICALES Y SUBTROPICALES (INCLUYE EL CULTIVO DE PALTAS)",
  },
  { codigo: "012300", nombre: "CULTIVO DE CÍTRICOS" },
  { codigo: "012400", nombre: "CULTIVO DE FRUTAS DE PEPITA Y DE HUESO" },
  { codigo: "012501", nombre: "CULTIVO DE SEMILLAS DE FRUTAS" },
  {
    codigo: "012502",
    nombre: "CULTIVO DE OTROS FRUTOS Y NUECES DE ÁRBOLES Y ARBUSTOS",
  },
  {
    codigo: "012600",
    nombre: "CULTIVO DE FRUTOS OLEAGINOSOS (INCLUYE EL CULTIVO DE ACEITUNAS)",
  },
  {
    codigo: "012700",
    nombre:
      "CULTIVO DE PLANTAS CON LAS QUE SE PREPARAN BEBIDAS (INCLUYE EL CULTIVO DE CAFÉ, TÉ Y MATE)",
  },
  { codigo: "012801", nombre: "CULTIVO DE ESPECIAS" },
  {
    codigo: "012802",
    nombre: "CULTIVO DE PLANTAS AROMÁTICAS, MEDICINALES Y FARMACÉUTICAS",
  },
  { codigo: "012900", nombre: "CULTIVO DE OTRAS PLANTAS PERENNES" },
  {
    codigo: "013000",
    nombre:
      "CULTIVO DE PLANTAS VIVAS INCLUIDA LA PRODUCCIÓN EN VIVEROS (EXCEPTO VIVEROS FORESTALES)",
  },
  {
    codigo: "014101",
    nombre: "CRÍA DE GANADO BOVINO PARA LA PRODUCCIÓN LECHERA",
  },
  {
    codigo: "014102",
    nombre:
      "CRÍA DE GANADO BOVINO PARA LA PRODUCCIÓN DE CARNE O COMO GANADO REPRODUCTOR",
  },
  { codigo: "014200", nombre: "CRÍA DE CABALLOS Y OTROS EQUINOS" },
  {
    codigo: "014300",
    nombre: "CRÍA DE LLAMAS, ALPACAS, VICUÑAS, GUANACOS Y OTROS CAMÉLIDOS",
  },
  { codigo: "014410", nombre: "CRÍA DE OVEJAS (OVINOS)" },
  { codigo: "014420", nombre: "CRÍA DE CABRAS (CAPRINOS)" },
  { codigo: "014500", nombre: "CRÍA DE CERDOS" },
  {
    codigo: "014601",
    nombre: "CRÍA DE AVES DE CORRAL PARA LA PRODUCCIÓN DE CARNE",
  },
  {
    codigo: "014602",
    nombre: "CRÍA DE AVES DE CORRAL PARA LA PRODUCCIÓN DE HUEVOS",
  },
  { codigo: "014901", nombre: "APICULTURA" },
  { codigo: "014909", nombre: "CRÍA DE OTROS ANIMALES N.C.P." },
  {
    codigo: "015000",
    nombre:
      "CULTIVO DE PRODUCTOS AGRÍCOLAS EN COMBINACIÓN CON LA CRÍA DE ANIMALES (EXPLOTACIÓN MIXTA)",
  },
  { codigo: "016100", nombre: "ACTIVIDADES DE APOYO A LA AGRICULTURA" },
  { codigo: "016200", nombre: "ACTIVIDADES DE APOYO A LA GANADERÍA" },
  { codigo: "016300", nombre: "ACTIVIDADES POSCOSECHA" },
  { codigo: "016400", nombre: "TRATAMIENTO DE SEMILLAS PARA PROPAGACIÓN" },
  {
    codigo: "017000",
    nombre:
      "CAZA ORDINARIA Y MEDIANTE TRAMPAS Y ACTIVIDADES DE SERVICIOS CONEXAS",
  },
  { codigo: "021001", nombre: "EXPLOTACIÓN DE VIVEROS FORESTALES" },
  {
    codigo: "021002",
    nombre:
      "SILVICULTURA Y OTRAS ACTIVIDADES FORESTALES (EXCEPTO EXPLOTACIÓN DE VIVEROS FORESTALES)",
  },
  { codigo: "022000", nombre: "EXTRACCIÓN DE MADERA" },
  {
    codigo: "023000",
    nombre: "RECOLECCIÓN DE PRODUCTOS FORESTALES DISTINTOS DE LA MADERA",
  },
  {
    codigo: "024001",
    nombre:
      "SERVICIOS DE FORESTACIÓN A CAMBIO DE UNA RETRIBUCIÓN O POR CONTRATA",
  },
  {
    codigo: "024002",
    nombre:
      "SERVICIOS DE CORTA DE MADERA A CAMBIO DE UNA RETRIBUCIÓN O POR CONTRATA",
  },
  {
    codigo: "024003",
    nombre: "SERVICIOS DE EXTINCIÓN Y PREVENCIÓN DE INCENDIOS FORESTALES",
  },
  {
    codigo: "024009",
    nombre: "OTROS SERVICIOS DE APOYO A LA SILVICULTURA N.C.P.",
  },
  {
    codigo: "031110",
    nombre: "PESCA MARÍTIMA INDUSTRIAL, EXCEPTO DE BARCOS FACTORÍA",
  },
  { codigo: "031120", nombre: "PESCA MARÍTIMA ARTESANAL" },
  { codigo: "031130", nombre: "RECOLECCIÓN Y EXTRACCIÓN DE PRODUCTOS MARINOS" },
  { codigo: "031140", nombre: "SERVICIOS RELACIONADOS CON LA PESCA MARÍTIMA" },
  { codigo: "031200", nombre: "PESCA DE AGUA DULCE" },
  { codigo: "032110", nombre: "CULTIVO Y CRIANZA DE PECES MARINOS" },
  {
    codigo: "032120",
    nombre: "CULTIVO, REPRODUCCIÓN Y MANEJO DE ALGAS MARINAS",
  },
  {
    codigo: "032130",
    nombre: "REPRODUCCIÓN Y CRÍA DE MOLUSCOS, CRUSTÁCEOS Y GUSANOS MARINOS",
  },
  {
    codigo: "032140",
    nombre: "SERVICIOS RELACIONADOS CON LA ACUICULTURA MARINA",
  },
  { codigo: "032200", nombre: "ACUICULTURA DE AGUA DULCE" },

  // EXPLOTACIÓN DE MINAS Y CANTERAS
  { codigo: "040000", nombre: "EXTRACCIÓN Y PROCESAMIENTO DE COBRE" },
  { codigo: "051000", nombre: "EXTRACCIÓN DE CARBÓN DE PIEDRA" },
  { codigo: "052000", nombre: "EXTRACCIÓN DE LIGNITO" },
  { codigo: "061000", nombre: "EXTRACCIÓN DE PETRÓLEO CRUDO" },
  { codigo: "062000", nombre: "EXTRACCIÓN DE GAS NATURAL" },
  { codigo: "071000", nombre: "EXTRACCIÓN DE MINERALES DE HIERRO" },
  { codigo: "072100", nombre: "EXTRACCIÓN DE MINERALES DE URANIO Y TORIO" },
  { codigo: "072910", nombre: "EXTRACCIÓN DE ORO Y PLATA" },
  { codigo: "072991", nombre: "EXTRACCIÓN DE ZINC Y PLOMO" },
  { codigo: "072992", nombre: "EXTRACCIÓN DE MANGANESO" },
  {
    codigo: "072999",
    nombre:
      "EXTRACCIÓN DE OTROS MINERALES METALÍFEROS NO FERROSOS N.C.P. (EXCEPTO ZINC, PLOMO Y MANGANESO)",
  },
  { codigo: "081000", nombre: "EXTRACCIÓN DE PIEDRA, ARENA Y ARCILLA" },
  { codigo: "089110", nombre: "EXTRACCIÓN Y PROCESAMIENTO DE LITIO" },
  {
    codigo: "089190",
    nombre:
      "EXTRACCIÓN DE MINERALES PARA LA FABRICACIÓN DE ABONOS Y PRODUCTOS QUÍMICOS N.C.P.",
  },
  { codigo: "089200", nombre: "EXTRACCIÓN DE TURBA" },
  { codigo: "089300", nombre: "EXTRACCIÓN DE SAL" },
  { codigo: "089900", nombre: "EXPLOTACIÓN DE OTRAS MINAS Y CANTERAS N.C.P." },
  {
    codigo: "091001",
    nombre:
      "ACTIVIDADES DE APOYO PARA LA EXTRACCIÓN DE PETRÓLEO Y GAS NATURAL PRESTADOS POR EMPRESAS",
  },
  {
    codigo: "091002",
    nombre:
      "ACTIVIDADES DE APOYO PARA LA EXTRACCIÓN DE PETRÓLEO Y GAS NATURAL PRESTADOS POR PROFESIONALES",
  },
  {
    codigo: "099001",
    nombre:
      "ACTIVIDADES DE APOYO PARA LA EXPLOTACIÓN DE OTRAS MINAS Y CANTERAS PRESTADOS POR EMPRESAS",
  },
  {
    codigo: "099002",
    nombre:
      "ACTIVIDADES DE APOYO PARA LA EXPLOTACIÓN DE OTRAS MINAS Y CANTERAS PRESTADOS POR PROFESIONALES",
  },

  // INDUSTRIA MANUFACTURERA
  {
    codigo: "101011",
    nombre:
      "EXPLOTACIÓN DE MATADEROS DE BOVINOS, OVINOS, EQUINOS, CAPRINOS, PORCINOS Y CAMÉLIDOS",
  },
  {
    codigo: "101019",
    nombre:
      "EXPLOTACIÓN DE MATADEROS DE AVES Y DE OTROS TIPOS DE ANIMALES N.C.P.",
  },
  {
    codigo: "101020",
    nombre: "ELABORACIÓN Y CONSERVACIÓN DE CARNE Y PRODUCTOS CÁRNICOS",
  },
  { codigo: "102010", nombre: "PRODUCCIÓN DE HARINA DE PESCADO" },
  { codigo: "102020", nombre: "ELABORACIÓN Y CONSERVACIÓN DE SALMÓNIDOS" },
  {
    codigo: "102030",
    nombre:
      "ELABORACIÓN Y CONSERVACIÓN DE OTROS PESCADOS, EN PLANTAS EN TIERRA (EXCEPTO BARCOS FACTORÍA)",
  },
  {
    codigo: "102040",
    nombre:
      "ELABORACIÓN Y CONSERVACIÓN DE CRUSTÁCEOS, MOLUSCOS Y OTROS PRODUCTOS ACUÁTICOS, EN PLANTAS EN TIERRA",
  },
  {
    codigo: "102050",
    nombre:
      "ACTIVIDADES DE ELABORACIÓN Y CONSERVACIÓN DE PESCADO, REALIZADAS EN BARCOS FACTORÍA",
  },
  { codigo: "102060", nombre: "ELABORACIÓN Y PROCESAMIENTO DE ALGAS" },
  {
    codigo: "103000",
    nombre: "ELABORACIÓN Y CONSERVACIÓN DE FRUTAS, LEGUMBRES Y HORTALIZAS",
  },
  {
    codigo: "104000",
    nombre:
      "ELABORACIÓN DE ACEITES Y GRASAS DE ORIGEN VEGETAL Y ANIMAL (EXCEPTO ELABORACIÓN DE MANTEQUILLA)",
  },
  { codigo: "105000", nombre: "ELABORACIÓN DE PRODUCTOS LÁCTEOS" },
  {
    codigo: "106101",
    nombre: "MOLIENDA DE TRIGO: PRODUCCIÓN DE HARINA, SÉMOLA Y GRÁNULOS",
  },
  {
    codigo: "106102",
    nombre: "MOLIENDA DE ARROZ; PRODUCCIÓN DE HARINA DE ARROZ",
  },
  {
    codigo: "106109",
    nombre: "ELABORACIÓN DE OTROS PRODUCTOS DE MOLINERÍA N.C.P.",
  },
  {
    codigo: "106200",
    nombre: "ELABORACIÓN DE ALMIDONES Y PRODUCTOS DERIVADOS DEL ALMIDÓN",
  },
  {
    codigo: "107100",
    nombre: "ELABORACIÓN DE PRODUCTOS DE PANADERÍA Y PASTELERÍA",
  },
  { codigo: "107200", nombre: "ELABORACIÓN DE AZÚCAR" },
  {
    codigo: "107300",
    nombre: "ELABORACIÓN DE CACAO, CHOCOLATE Y DE PRODUCTOS DE CONFITERÍA",
  },
  {
    codigo: "107400",
    nombre:
      "ELABORACIÓN DE MACARRONES, FIDEOS, ALCUZCUZ Y PRODUCTOS FARINÁCEOS SIMILARES",
  },
  {
    codigo: "107500",
    nombre:
      "ELABORACIÓN DE COMIDAS Y PLATOS PREPARADOS ENVASADOS, ROTULADOS Y CON INFORMACIÓN NUTRICIONAL",
  },
  {
    codigo: "107901",
    nombre: "ELABORACIÓN DE TÉ, CAFÉ, MATE E INFUSIONES DE HIERBAS",
  },
  {
    codigo: "107902",
    nombre: "ELABORACIÓN DE LEVADURAS NATURALES O ARTIFICIALES",
  },
  {
    codigo: "107903",
    nombre:
      "ELABORACIÓN DE VINAGRES, MOSTAZAS, MAYONESAS Y CONDIMENTOS EN GENERAL",
  },
  {
    codigo: "107909",
    nombre: "ELABORACIÓN DE OTROS PRODUCTOS ALIMENTICIOS N.C.P.",
  },
  {
    codigo: "108000",
    nombre: "ELABORACIÓN DE PIENSOS PREPARADOS PARA ANIMALES",
  },
  { codigo: "110110", nombre: "ELABORACIÓN DE PISCO (INDUSTRIAS PISQUERAS)" },
  {
    codigo: "110120",
    nombre:
      "DESTILACIÓN, RECTIFICACIÓN Y MEZCLAS DE BEBIDAS ALCOHÓLICAS; EXCEPTO PISCO",
  },
  { codigo: "110200", nombre: "ELABORACIÓN DE VINOS" },
  { codigo: "110300", nombre: "ELABORACIÓN DE BEBIDAS MALTEADAS Y DE MALTA" },
  { codigo: "110401", nombre: "ELABORACIÓN DE BEBIDAS NO ALCOHÓLICAS" },
  {
    codigo: "110402",
    nombre: "PRODUCCIÓN DE AGUAS MINERALES Y OTRAS AGUAS EMBOTELLADAS",
  },
  { codigo: "120001", nombre: "ELABORACIÓN DE CIGARROS Y CIGARRILLOS" },
  {
    codigo: "120009",
    nombre: "ELABORACIÓN DE OTROS PRODUCTOS DE TABACO N.C.P.",
  },
  { codigo: "131100", nombre: "PREPARACIÓN E HILATURA DE FIBRAS TEXTILES" },
  { codigo: "131200", nombre: "TEJEDURA DE PRODUCTOS TEXTILES" },
  { codigo: "131300", nombre: "ACABADO DE PRODUCTOS TEXTILES" },
  { codigo: "139100", nombre: "FABRICACIÓN DE TEJIDOS DE PUNTO Y GANCHILLO" },
  {
    codigo: "139200",
    nombre:
      "FABRICACIÓN DE ARTÍCULOS CONFECCIONADOS DE MATERIALES TEXTILES, EXCEPTO PRENDAS DE VESTIR",
  },
  { codigo: "139300", nombre: "FABRICACIÓN DE TAPICES Y ALFOMBRAS" },
  {
    codigo: "139400",
    nombre: "FABRICACIÓN DE CUERDAS, CORDELES, BRAMANTES Y REDES",
  },
  {
    codigo: "139900",
    nombre: "FABRICACIÓN DE OTROS PRODUCTOS TEXTILES N.C.P.",
  },
  {
    codigo: "141001",
    nombre:
      "FABRICACIÓN DE PRENDAS DE VESTIR DE MATERIALES TEXTILES Y SIMILARES",
  },
  {
    codigo: "141002",
    nombre: "FABRICACIÓN DE PRENDAS DE VESTIR DE CUERO NATURAL O ARTIFICIAL",
  },
  { codigo: "141003", nombre: "FABRICACIÓN DE ACCESORIOS DE VESTIR" },
  { codigo: "141004", nombre: "FABRICACIÓN DE ROPA DE TRABAJO" },
  { codigo: "142000", nombre: "FABRICACIÓN DE ARTÍCULOS DE PIEL" },
  { codigo: "143000", nombre: "FABRICACIÓN DE ARTÍCULOS DE PUNTO Y GANCHILLO" },
  {
    codigo: "151100",
    nombre: "CURTIDO Y ADOBO DE CUEROS; ADOBO Y TEÑIDO DE PIELES",
  },
  {
    codigo: "151200",
    nombre:
      "FABRICACIÓN DE MALETAS, BOLSOS Y ARTÍCULOS SIMILARES, ARTÍCULOS DE TALABARTERÍA Y GUARNICIONERÍA",
  },
  { codigo: "152000", nombre: "FABRICACIÓN DE CALZADO" },
  { codigo: "161000", nombre: "ASERRADO Y ACEPILLADURA DE MADERA" },
  {
    codigo: "162100",
    nombre:
      "FABRICACIÓN DE HOJAS DE MADERA PARA ENCHAPADO Y TABLEROS A BASE DE MADERA",
  },
  {
    codigo: "162200",
    nombre:
      "FABRICACIÓN DE PARTES Y PIEZAS DE CARPINTERÍA PARA EDIFICIOS Y CONSTRUCCIONES",
  },
  { codigo: "162300", nombre: "FABRICACIÓN DE RECIPIENTES DE MADERA" },
  {
    codigo: "162900",
    nombre:
      "FABRICACIÓN DE OTROS PRODUCTOS DE MADERA, DE ARTÍCULOS DE CORCHO, PAJA Y MATERIALES TRENZABLES",
  },
  {
    codigo: "170110",
    nombre: "FABRICACIÓN DE CELULOSA Y OTRAS PASTAS DE MADERA",
  },
  {
    codigo: "170190",
    nombre:
      "FABRICACIÓN DE PAPEL Y CARTÓN PARA SU POSTERIOR USO INDUSTRIAL N.C.P.",
  },
  {
    codigo: "170200",
    nombre:
      "FABRICACIÓN DE PAPEL Y CARTÓN ONDULADO Y DE ENVASES DE PAPEL Y CARTÓN",
  },
  {
    codigo: "170900",
    nombre: "FABRICACIÓN DE OTROS ARTÍCULOS DE PAPEL Y CARTÓN",
  },
  { codigo: "181101", nombre: "IMPRESIÓN DE LIBROS" },
  { codigo: "181109", nombre: "OTRAS ACTIVIDADES DE IMPRESIÓN N.C.P." },
  {
    codigo: "181200",
    nombre: "ACTIVIDADES DE SERVICIOS RELACIONADAS CON LA IMPRESIÓN",
  },
  { codigo: "182000", nombre: "REPRODUCCIÓN DE GRABACIONES" },
  { codigo: "191000", nombre: "FABRICACIÓN DE PRODUCTOS DE HORNOS DE COQUE" },
  {
    codigo: "192000",
    nombre: "FABRICACIÓN DE PRODUCTOS DE LA REFINACIÓN DEL PETRÓLEO",
  },
  {
    codigo: "201101",
    nombre:
      "FABRICACIÓN DE CARBÓN VEGETAL (EXCEPTO ACTIVADO); FABRICACIÓN DE BRIQUETAS DE CARBÓN VEGETAL",
  },
  {
    codigo: "201109",
    nombre: "FABRICACIÓN DE OTRAS SUSTANCIAS QUÍMICAS BÁSICAS N.C.P.",
  },
  {
    codigo: "201200",
    nombre: "FABRICACIÓN DE ABONOS Y COMPUESTOS DE NITRÓGENO",
  },
  {
    codigo: "201300",
    nombre: "FABRICACIÓN DE PLÁSTICOS Y CAUCHO SINTÉTICO EN FORMAS PRIMARIAS",
  },
  {
    codigo: "202100",
    nombre:
      "FABRICACIÓN DE PLAGUICIDAS Y OTROS PRODUCTOS QUÍMICOS DE USO AGROPECUARIO",
  },
  {
    codigo: "202200",
    nombre:
      "FABRICACIÓN DE PINTURAS, BARNICES Y PRODUCTOS DE REVESTIMIENTO, TINTAS DE IMPRENTA Y MASILLAS",
  },
  {
    codigo: "202300",
    nombre:
      "FABRICACIÓN DE JABONES Y DETERGENTES, PREPARADOS PARA LIMPIAR, PERFUMES Y PREPARADOS DE TOCADOR",
  },
  {
    codigo: "202901",
    nombre: "FABRICACIÓN DE EXPLOSIVOS Y PRODUCTOS PIROTÉCNICOS",
  },
  {
    codigo: "202909",
    nombre: "FABRICACIÓN DE OTROS PRODUCTOS QUÍMICOS N.C.P.",
  },
  { codigo: "203000", nombre: "FABRICACIÓN DE FIBRAS ARTIFICIALES" },
  {
    codigo: "210000",
    nombre:
      "FABRICACIÓN DE PRODUCTOS FARMACÉUTICOS, SUSTANCIAS QUÍMICAS MEDICINALES Y PRODUCTOS BOTÁNICOS",
  },
  {
    codigo: "221100",
    nombre:
      "FABRICACIÓN DE CUBIERTAS Y CÁMARAS DE CAUCHO; RECAUCHUTADO Y RENOVACIÓN DE CUBIERTAS DE CAUCHO",
  },
  { codigo: "221900", nombre: "FABRICACIÓN DE OTROS PRODUCTOS DE CAUCHO" },
  { codigo: "222000", nombre: "FABRICACIÓN DE PRODUCTOS DE PLÁSTICO" },
  { codigo: "231001", nombre: "FABRICACIÓN DE VIDRIO PLANO" },
  { codigo: "231002", nombre: "FABRICACIÓN DE VIDRIO HUECO" },
  { codigo: "231003", nombre: "FABRICACIÓN DE FIBRAS DE VIDRIO" },
  { codigo: "231009", nombre: "FABRICACIÓN DE PRODUCTOS DE VIDRIO N.C.P." },
  { codigo: "239100", nombre: "FABRICACIÓN DE PRODUCTOS REFRACTARIOS" },
  {
    codigo: "239200",
    nombre: "FABRICACIÓN DE MATERIALES DE CONSTRUCCIÓN DE ARCILLA",
  },
  {
    codigo: "239300",
    nombre: "FABRICACIÓN DE OTROS PRODUCTOS DE PORCELANA Y DE CERÁMICA",
  },
  { codigo: "239400", nombre: "FABRICACIÓN DE CEMENTO, CAL Y YESO" },
  {
    codigo: "239500",
    nombre: "FABRICACIÓN DE ARTÍCULOS DE HORMIGÓN, CEMENTO Y YESO",
  },
  { codigo: "239600", nombre: "CORTE, TALLA Y ACABADO DE LA PIEDRA" },
  {
    codigo: "239900",
    nombre: "FABRICACIÓN DE OTROS PRODUCTOS MINERALES NO METÁLICOS N.C.P.",
  },
  { codigo: "241000", nombre: "INDUSTRIAS BÁSICAS DE HIERRO Y ACERO" },
  { codigo: "242001", nombre: "FABRICACIÓN DE PRODUCTOS PRIMARIOS DE COBRE" },
  {
    codigo: "242002",
    nombre: "FABRICACIÓN DE PRODUCTOS PRIMARIOS DE ALUMINIO",
  },
  {
    codigo: "242009",
    nombre:
      "FABRICACIÓN DE PRODUCTOS PRIMARIOS DE METALES PRECIOSOS Y DE OTROS METALES NO FERROSOS N.C.P.",
  },
  { codigo: "243100", nombre: "FUNDICIÓN DE HIERRO Y ACERO" },
  { codigo: "243200", nombre: "FUNDICIÓN DE METALES NO FERROSOS" },
  {
    codigo: "251100",
    nombre: "FABRICACIÓN DE PRODUCTOS METÁLICOS PARA USO ESTRUCTURAL",
  },
  {
    codigo: "251201",
    nombre:
      "FABRICACIÓN DE RECIPIENTES DE METAL PARA GASES COMPRIMIDOS O LICUADOS",
  },
  {
    codigo: "251209",
    nombre: "FABRICACIÓN DE TANQUES, DEPÓSITOS Y RECIPIENTES DE METAL N.C.P.",
  },
  {
    codigo: "251300",
    nombre:
      "FABRICACIÓN DE GENERADORES DE VAPOR, EXCEPTO CALDERAS DE AGUA CALIENTE PARA CALEFACCIÓN CENTRAL",
  },
  { codigo: "252000", nombre: "FABRICACIÓN DE ARMAS Y MUNICIONES" },
  {
    codigo: "259100",
    nombre: "FORJA, PRENSADO, ESTAMPADO Y LAMINADO DE METALES; PULVIMETALURGIA",
  },
  {
    codigo: "259200",
    nombre: "TRATAMIENTO Y REVESTIMIENTO DE METALES; MAQUINADO",
  },
  {
    codigo: "259300",
    nombre:
      "FABRICACIÓN DE ARTÍCULOS DE CUCHILLERÍA, HERRAMIENTAS DE MANO Y ARTÍCULOS DE FERRETERÍA",
  },
  {
    codigo: "259900",
    nombre: "FABRICACIÓN DE OTROS PRODUCTOS ELABORADOS DE METAL N.C.P.",
  },
  {
    codigo: "261000",
    nombre: "FABRICACIÓN DE COMPONENTES Y TABLEROS ELECTRÓNICOS",
  },
  {
    codigo: "262000",
    nombre: "FABRICACIÓN DE COMPUTADORES Y EQUIPO PERIFÉRICO",
  },
  { codigo: "263000", nombre: "FABRICACIÓN DE EQUIPO DE COMUNICACIONES" },
  {
    codigo: "264000",
    nombre: "FABRICACIÓN DE APARATOS ELECTRÓNICOS DE CONSUMO",
  },
  {
    codigo: "265100",
    nombre: "FABRICACIÓN DE EQUIPO DE MEDICIÓN, PRUEBA, NAVEGACIÓN Y CONTROL",
  },
  { codigo: "265200", nombre: "FABRICACIÓN DE RELOJES" },
  {
    codigo: "266000",
    nombre:
      "FABRICACIÓN DE EQUIPO DE IRRADIACIÓN Y EQUIPO ELECTRÓNICO DE USO MÉDICO Y TERAPÉUTICO",
  },
  {
    codigo: "267000",
    nombre: "FABRICACIÓN DE INSTRUMENTOS ÓPTICOS Y EQUIPO FOTOGRÁFICO",
  },
  { codigo: "268000", nombre: "FABRICACIÓN DE SOPORTES MAGNÉTICOS Y ÓPTICOS" },
  {
    codigo: "271000",
    nombre:
      "FABRICACIÓN DE MOTORES, GENERADORES Y TRANSFORMADORES ELÉCTRICOS, APARATOS DE DISTRIBUCIÓN Y CONTROL",
  },
  { codigo: "272000", nombre: "FABRICACIÓN DE PILAS, BATERÍAS Y ACUMULADORES" },
  { codigo: "273100", nombre: "FABRICACIÓN DE CABLES DE FIBRA ÓPTICA" },
  {
    codigo: "273200",
    nombre: "FABRICACIÓN DE OTROS HILOS Y CABLES ELÉCTRICOS",
  },
  { codigo: "273300", nombre: "FABRICACIÓN DE DISPOSITIVOS DE CABLEADO" },
  {
    codigo: "274000",
    nombre: "FABRICACIÓN DE EQUIPO ELÉCTRICO DE ILUMINACIÓN",
  },
  { codigo: "275000", nombre: "FABRICACIÓN DE APARATOS DE USO DOMÉSTICO" },
  {
    codigo: "279000",
    nombre: "FABRICACIÓN DE OTROS TIPOS DE EQUIPO ELÉCTRICO",
  },
  {
    codigo: "281100",
    nombre:
      "FABRICACIÓN DE MOTORES Y TURBINAS, EXCEPTO PARA AERONAVES, VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS",
  },
  {
    codigo: "281200",
    nombre: "FABRICACIÓN DE EQUIPO DE PROPULSIÓN DE FLUIDOS",
  },
  {
    codigo: "281300",
    nombre: "FABRICACIÓN DE OTRAS BOMBAS, COMPRESORES, GRIFOS Y VÁLVULAS",
  },
  {
    codigo: "281400",
    nombre:
      "FABRICACIÓN DE COJINETES, ENGRANAJES, TRENES DE ENGRANAJES Y PIEZAS DE TRANSMISIÓN",
  },
  { codigo: "281500", nombre: "FABRICACIÓN DE HORNOS, CALDERAS Y QUEMADORES" },
  {
    codigo: "281600",
    nombre: "FABRICACIÓN DE EQUIPO DE ELEVACIÓN Y MANIPULACIÓN",
  },
  {
    codigo: "281700",
    nombre:
      "FABRICACIÓN DE MAQUINARIA Y EQUIPO DE OFICINA (EXCEPTO COMPUTADORES Y EQUIPO PERIFÉRICO)",
  },
  {
    codigo: "281800",
    nombre: "FABRICACIÓN DE HERRAMIENTAS DE MANO MOTORIZADAS",
  },
  {
    codigo: "281900",
    nombre: "FABRICACIÓN DE OTROS TIPOS DE MAQUINARIA DE USO GENERAL",
  },
  {
    codigo: "282100",
    nombre: "FABRICACIÓN DE MAQUINARIA AGROPECUARIA Y FORESTAL",
  },
  {
    codigo: "282200",
    nombre:
      "FABRICACIÓN DE MAQUINARIA PARA LA CONFORMACIÓN DE METALES Y DE MÁQUINAS HERRAMIENTA",
  },
  { codigo: "282300", nombre: "FABRICACIÓN DE MAQUINARIA METALÚRGICA" },
  {
    codigo: "282400",
    nombre:
      "FABRICACIÓN DE MAQUINARIA PARA LA EXPLOTACIÓN DE MINAS Y CANTERAS Y PARA OBRAS DE CONSTRUCCIÓN",
  },
  {
    codigo: "282500",
    nombre:
      "FABRICACIÓN DE MAQUINARIA PARA LA ELABORACIÓN DE ALIMENTOS, BEBIDAS Y TABACO",
  },
  {
    codigo: "282600",
    nombre:
      "FABRICACIÓN DE MAQUINARIA PARA LA ELABORACIÓN DE PRODUCTOS TEXTILES, PRENDAS DE VESTIR Y CUEROS",
  },
  {
    codigo: "282900",
    nombre: "FABRICACIÓN DE OTROS TIPOS DE MAQUINARIA DE USO ESPECIAL",
  },
  { codigo: "291000", nombre: "FABRICACIÓN DE VEHÍCULOS AUTOMOTORES" },
  {
    codigo: "292000",
    nombre:
      "FABRICACIÓN DE CARROCERÍAS PARA VEHÍCULOS AUTOMOTORES; FABRICACIÓN DE REMOLQUES Y SEMIRREMOLQUES",
  },
  {
    codigo: "293000",
    nombre:
      "FABRICACIÓN DE PARTES, PIEZAS Y ACCESORIOS PARA VEHÍCULOS AUTOMOTORES",
  },
  {
    codigo: "301100",
    nombre:
      "CONSTRUCCIÓN DE BUQUES, EMBARCACIONES MENORES Y ESTRUCTURAS FLOTANTES",
  },
  {
    codigo: "301200",
    nombre: "CONSTRUCCIÓN DE EMBARCACIONES DE RECREO Y DE DEPORTE",
  },
  { codigo: "302000", nombre: "FABRICACIÓN DE LOCOMOTORAS Y MATERIAL RODANTE" },
  {
    codigo: "303000",
    nombre: "FABRICACIÓN DE AERONAVES, NAVES ESPACIALES Y MAQUINARIA CONEXA",
  },
  { codigo: "304000", nombre: "FABRICACIÓN DE VEHÍCULOS MILITARES DE COMBATE" },
  { codigo: "309100", nombre: "FABRICACIÓN DE MOTOCICLETAS" },
  {
    codigo: "309200",
    nombre: "FABRICACIÓN DE BICICLETAS Y DE SILLAS DE RUEDAS",
  },
  {
    codigo: "309900",
    nombre: "FABRICACIÓN DE OTROS TIPOS DE EQUIPO DE TRANSPORTE N.C.P.",
  },
  {
    codigo: "310001",
    nombre: "FABRICACIÓN DE MUEBLES PRINCIPALMENTE DE MADERA",
  },
  {
    codigo: "310009",
    nombre: "FABRICACIÓN DE COLCHONES; FABRICACIÓN DE OTROS MUEBLES N.C.P.",
  },
  { codigo: "321100", nombre: "FABRICACIÓN DE JOYAS Y ARTÍCULOS CONEXOS" },
  { codigo: "321200", nombre: "FABRICACIÓN DE BISUTERÍA Y ARTÍCULOS CONEXOS" },
  { codigo: "322000", nombre: "FABRICACIÓN DE INSTRUMENTOS MUSICALES" },
  { codigo: "323000", nombre: "FABRICACIÓN DE ARTÍCULOS DE DEPORTE" },
  { codigo: "324000", nombre: "FABRICACIÓN DE JUEGOS Y JUGUETES" },
  { codigo: "325001", nombre: "ACTIVIDADES DE LABORATORIOS DENTALES" },
  {
    codigo: "325009",
    nombre:
      "FABRICACIÓN DE INSTRUMENTOS Y MATERIALES MÉDICOS, OFTALMOLÓGICOS Y ODONTOLÓGICOS N.C.P.",
  },
  { codigo: "329000", nombre: "OTRAS INDUSTRIAS MANUFACTURERAS N.C.P." },
  { codigo: "331100", nombre: "REPARACIÓN DE PRODUCTOS ELABORADOS DE METAL" },
  {
    codigo: "331201",
    nombre: "REPARACIÓN DE MAQUINARIA AGROPECUARIA Y FORESTAL",
  },
  {
    codigo: "331202",
    nombre:
      "REPARACIÓN DE MAQUINARIA METALÚRGICA, PARA LA MINERÍA, EXTRACCIÓN DE PETRÓLEO Y PARA LA CONSTRUCCIÓN",
  },
  {
    codigo: "331203",
    nombre:
      "REPARACIÓN DE MAQUINARIA PARA LA ELABORACIÓN DE ALIMENTOS, BEBIDAS Y TABACO",
  },
  {
    codigo: "331204",
    nombre:
      "REPARACIÓN DE MAQUINARIA PARA PRODUCIR TEXTILES, PRENDAS DE VESTIR, ARTÍCULOS DE CUERO Y CALZADO",
  },
  {
    codigo: "331209",
    nombre:
      "REPARACIÓN DE OTRO TIPO DE MAQUINARIA Y EQUIPOS INDUSTRIALES N.C.P.",
  },
  {
    codigo: "331301",
    nombre: "REPARACIÓN DE EQUIPO DE MEDICIÓN, PRUEBA, NAVEGACIÓN Y CONTROL",
  },
  {
    codigo: "331309",
    nombre: "REPARACIÓN DE OTROS EQUIPOS ELECTRÓNICOS Y ÓPTICOS N.C.P.",
  },
  {
    codigo: "331400",
    nombre:
      "REPARACIÓN DE EQUIPO ELÉCTRICO (EXCEPTO REPARACIÓN DE EQUIPO Y ENSERES DOMÉSTICOS)",
  },
  {
    codigo: "331501",
    nombre:
      "REPARACIÓN DE BUQUES, EMBARCACIONES MENORES Y ESTRUCTURAS FLOTANTES",
  },
  { codigo: "331502", nombre: "REPARACIÓN DE AERONAVES Y NAVES ESPACIALES" },
  {
    codigo: "331509",
    nombre:
      "REPARACIÓN DE OTROS EQUIPOS DE TRANSPORTE N.C.P., EXCEPTO VEHÍCULOS AUTOMOTORES",
  },
  { codigo: "331900", nombre: "REPARACIÓN DE OTROS TIPOS DE EQUIPO" },
  {
    codigo: "332000",
    nombre: "INSTALACIÓN DE MAQUINARIA Y EQUIPOS INDUSTRIALES",
  },

  // SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO
  {
    codigo: "351011",
    nombre: "GENERACIÓN DE ENERGÍA ELÉCTRICA EN CENTRALES HIDROELÉCTRICAS",
  },
  {
    codigo: "351012",
    nombre: "GENERACIÓN DE ENERGÍA ELÉCTRICA EN CENTRALES TERMOELÉCTRICAS",
  },
  {
    codigo: "351019",
    nombre: "GENERACIÓN DE ENERGÍA ELÉCTRICA EN OTRAS CENTRALES N.C.P.",
  },
  { codigo: "351020", nombre: "TRANSMISIÓN DE ENERGÍA ELÉCTRICA" },
  { codigo: "351030", nombre: "DISTRIBUCIÓN DE ENERGÍA ELÉCTRICA" },
  { codigo: "352010", nombre: "REGASIFICACIÓN DE GAS NATURAL LICUADO (GNL)" },
  {
    codigo: "352020",
    nombre:
      "FABRICACIÓN DE GAS; DISTRIBUCIÓN DE COMBUSTIBLES GASEOSOS POR TUBERÍA, EXCEPTO REGASIFICACIÓN DE GNL",
  },
  { codigo: "353001", nombre: "SUMINISTRO DE VAPOR Y DE AIRE ACONDICIONADO" },
  {
    codigo: "353002",
    nombre: "ELABORACIÓN DE HIELO (EXCEPTO FABRICACIÓN DE HIELO SECO)",
  },

  // SUMINISTRO DE AGUA; EVACUACIÓN DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS Y DESCONTAMINACIÓN
  { codigo: "360000", nombre: "CAPTACIÓN, TRATAMIENTO Y DISTRIBUCIÓN DE AGUA" },
  { codigo: "370000", nombre: "EVACUACIÓN Y TRATAMIENTO DE AGUAS SERVIDAS" },
  { codigo: "381100", nombre: "RECOGIDA DE DESECHOS NO PELIGROSOS" },
  { codigo: "381200", nombre: "RECOGIDA DE DESECHOS PELIGROSOS" },
  {
    codigo: "382100",
    nombre: "TRATAMIENTO Y ELIMINACIÓN DE DESECHOS NO PELIGROSOS",
  },
  {
    codigo: "382200",
    nombre: "TRATAMIENTO Y ELIMINACIÓN DE DESECHOS PELIGROSOS",
  },
  {
    codigo: "383001",
    nombre: "RECUPERACIÓN Y RECICLAMIENTO DE DESPERDICIOS Y DESECHOS METÁLICOS",
  },
  { codigo: "383002", nombre: "RECUPERACIÓN Y RECICLAMIENTO DE PAPEL" },
  { codigo: "383003", nombre: "RECUPERACIÓN Y RECICLAMIENTO DE VIDRIO" },
  {
    codigo: "383009",
    nombre:
      "RECUPERACIÓN Y RECICLAMIENTO DE OTROS DESPERDICIOS Y DESECHOS N.C.P.",
  },
  {
    codigo: "390000",
    nombre:
      "ACTIVIDADES DE DESCONTAMINACIÓN Y OTROS SERVICIOS DE GESTIÓN DE DESECHOS",
  },

  // CONSTRUCCIÓN
  {
    codigo: "410010",
    nombre: "CONSTRUCCIÓN DE EDIFICIOS PARA USO RESIDENCIAL",
  },
  {
    codigo: "410020",
    nombre: "CONSTRUCCIÓN DE EDIFICIOS PARA USO NO RESIDENCIAL",
  },
  {
    codigo: "421000",
    nombre: "CONSTRUCCIÓN DE CARRETERAS Y LÍNEAS DE FERROCARRIL",
  },
  { codigo: "422000", nombre: "CONSTRUCCIÓN DE PROYECTOS DE SERVICIO PÚBLICO" },
  {
    codigo: "429000",
    nombre: "CONSTRUCCIÓN DE OTRAS OBRAS DE INGENIERÍA CIVIL",
  },
  { codigo: "431100", nombre: "DEMOLICIÓN" },
  { codigo: "431200", nombre: "PREPARACIÓN DEL TERRENO" },
  { codigo: "432100", nombre: "INSTALACIONES ELÉCTRICAS" },
  {
    codigo: "432200",
    nombre: "INSTALACIONES DE GASFITERÍA, CALEFACCIÓN Y AIRE ACONDICIONADO",
  },
  {
    codigo: "432900",
    nombre: "OTRAS INSTALACIONES PARA OBRAS DE CONSTRUCCIÓN",
  },
  { codigo: "433000", nombre: "TERMINACIÓN Y ACABADO DE EDIFICIOS" },
  {
    codigo: "439000",
    nombre: "OTRAS ACTIVIDADES ESPECIALIZADAS DE CONSTRUCCIÓN",
  },

  // COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHICULOS AUTOMOTORES Y MOTOCICLETAS
  { codigo: "451001", nombre: "VENTA AL POR MAYOR DE VEHÍCULOS AUTOMOTORES" },
  {
    codigo: "451002",
    nombre:
      "VENTA AL POR MENOR DE VEHÍCULOS AUTOMOTORES NUEVOS O USADOS (INCLUYE COMPRAVENTA)",
  },
  { codigo: "452001", nombre: "SERVICIO DE LAVADO DE VEHÍCULOS AUTOMOTORES" },
  {
    codigo: "452002",
    nombre: "MANTENIMIENTO Y REPARACIÓN DE VEHÍCULOS AUTOMOTORES",
  },
  {
    codigo: "453000",
    nombre: "VENTA DE PARTES, PIEZAS Y ACCESORIOS PARA VEHÍCULOS AUTOMOTORES",
  },
  { codigo: "454001", nombre: "VENTA DE MOTOCICLETAS" },
  {
    codigo: "454002",
    nombre: "VENTA DE PARTES, PIEZAS Y ACCESORIOS DE MOTOCICLETAS",
  },
  { codigo: "454003", nombre: "MANTENIMIENTO Y REPARACIÓN DE MOTOCICLETAS" },
  { codigo: "461001", nombre: "CORRETAJE AL POR MAYOR DE PRODUCTOS AGRÍCOLAS" },
  { codigo: "461002", nombre: "CORRETAJE AL POR MAYOR DE GANADO" },
  {
    codigo: "461009",
    nombre: "OTROS TIPOS DE CORRETAJES O REMATES AL POR MAYOR N.C.P.",
  },
  {
    codigo: "462010",
    nombre: "VENTA AL POR MAYOR DE MATERIAS PRIMAS AGRÍCOLAS",
  },
  { codigo: "462020", nombre: "VENTA AL POR MAYOR DE ANIMALES VIVOS" },
  {
    codigo: "462090",
    nombre: "VENTA AL POR MAYOR DE OTRAS MATERIAS PRIMAS AGROPECUARIAS N.C.P.",
  },
  { codigo: "463011", nombre: "VENTA AL POR MAYOR DE FRUTAS Y VERDURAS" },
  {
    codigo: "463012",
    nombre: "VENTA AL POR MAYOR DE CARNE Y PRODUCTOS CÁRNICOS",
  },
  {
    codigo: "463013",
    nombre:
      "VENTA AL POR MAYOR DE PRODUCTOS DEL MAR (PESCADOS, MARISCOS Y ALGAS)",
  },
  { codigo: "463014", nombre: "VENTA AL POR MAYOR DE PRODUCTOS DE CONFITERÍA" },
  {
    codigo: "463019",
    nombre:
      "VENTA AL POR MAYOR DE HUEVOS, LÁCTEOS, ABARROTES Y DE OTROS ALIMENTOS N.C.P.",
  },
  {
    codigo: "463020",
    nombre: "VENTA AL POR MAYOR DE BEBIDAS ALCOHÓLICAS Y NO ALCOHÓLICAS",
  },
  { codigo: "463030", nombre: "VENTA AL POR MAYOR DE TABACO" },
  {
    codigo: "464100",
    nombre:
      "VENTA AL POR MAYOR DE PRODUCTOS TEXTILES, PRENDAS DE VESTIR Y CALZADO",
  },
  {
    codigo: "464901",
    nombre: "VENTA AL POR MAYOR DE MUEBLES, EXCEPTO MUEBLES DE OFICINA",
  },
  {
    codigo: "464902",
    nombre:
      "VENTA AL POR MAYOR DE ARTÍCULOS ELÉCTRICOS Y ELECTRÓNICOS PARA EL HOGAR",
  },
  {
    codigo: "464903",
    nombre:
      "VENTA AL POR MAYOR DE ARTÍCULOS DE PERFUMERÍA, DE TOCADOR Y COSMÉTICOS",
  },
  {
    codigo: "464904",
    nombre: "VENTA AL POR MAYOR DE ARTÍCULOS DE PAPELERÍA Y ESCRITORIO",
  },
  { codigo: "464905", nombre: "VENTA AL POR MAYOR DE LIBROS" },
  { codigo: "464906", nombre: "VENTA AL POR MAYOR DE DIARIOS Y REVISTAS" },
  {
    codigo: "464907",
    nombre: "VENTA AL POR MAYOR DE PRODUCTOS FARMACÉUTICOS Y MEDICINALES",
  },
  {
    codigo: "464908",
    nombre: "VENTA AL POR MAYOR DE INSTRUMENTOS CIENTÍFICOS Y QUIRÚRGICOS",
  },
  {
    codigo: "464909",
    nombre: "VENTA AL POR MAYOR DE OTROS ENSERES DOMÉSTICOS N.C.P.",
  },
  {
    codigo: "465100",
    nombre:
      "VENTA AL POR MAYOR DE COMPUTADORES, EQUIPO PERIFÉRICO Y PROGRAMAS INFORMÁTICOS",
  },
  {
    codigo: "465200",
    nombre:
      "VENTA AL POR MAYOR DE EQUIPO, PARTES Y PIEZAS ELECTRÓNICOS Y DE TELECOMUNICACIONES",
  },
  {
    codigo: "465300",
    nombre:
      "VENTA AL POR MAYOR DE MAQUINARIA, EQUIPO Y MATERIALES AGROPECUARIOS",
  },
  {
    codigo: "465901",
    nombre:
      "VENTA AL POR MAYOR DE MAQUINARIA METALÚRGICA, PARA LA MINERÍA, EXTRACCIÓN DE PETRÓLEO Y CONSTRUCCIÓN",
  },
  {
    codigo: "465902",
    nombre:
      "VENTA AL POR MAYOR DE MAQUINARIA PARA LA ELABORACIÓN DE ALIMENTOS, BEBIDAS Y TABACO",
  },
  {
    codigo: "465903",
    nombre:
      "VENTA AL POR MAYOR DE MAQUINARIA PARA LA INDUSTRIA TEXTIL, DEL CUERO Y DEL CALZADO",
  },
  {
    codigo: "465904",
    nombre:
      "VENTA AL POR MAYOR DE MAQUINARIA Y EQUIPO DE OFICINA; VENTA AL POR MAYOR DE MUEBLES DE OFICINA",
  },
  {
    codigo: "465905",
    nombre:
      "VENTA AL POR MAYOR DE EQUIPO DE TRANSPORTE(EXCEPTO VEHÍCULOS AUTOMOTORES, MOTOCICLETAS Y BICICLETAS)",
  },
  {
    codigo: "465909",
    nombre: "VENTA AL POR MAYOR DE OTROS TIPOS DE MAQUINARIA Y EQUIPO N.C.P.",
  },
  {
    codigo: "466100",
    nombre:
      "VENTA AL POR MAYOR DE COMBUSTIBLES SÓLIDOS, LÍQUIDOS Y GASEOSOS Y PRODUCTOS CONEXOS",
  },
  {
    codigo: "466200",
    nombre: "VENTA AL POR MAYOR DE METALES Y MINERALES METALÍFEROS",
  },
  {
    codigo: "466301",
    nombre:
      "VENTA AL POR MAYOR DE MADERA EN BRUTO Y PRODUCTOS PRIMARIOS DE LA ELABORACIÓN DE MADERA",
  },
  {
    codigo: "466302",
    nombre:
      "VENTA AL POR MAYOR DE MATERIALES DE CONSTRUCCIÓN, ARTÍCULOS DE FERRETERÍA, GASFITERÍA Y CALEFACCIÓN",
  },
  { codigo: "466901", nombre: "VENTA AL POR MAYOR DE PRODUCTOS QUÍMICOS" },
  {
    codigo: "466902",
    nombre: "VENTA AL POR MAYOR DE DESECHOS METÁLICOS (CHATARRA)",
  },
  {
    codigo: "466909",
    nombre:
      "VENTA AL POR MAYOR DE DESPERDICIOS, DESECHOS Y OTROS PRODUCTOS N.C.P.",
  },
  { codigo: "469000", nombre: "VENTA AL POR MAYOR NO ESPECIALIZADA" },
  {
    codigo: "471100",
    nombre:
      "VENTA AL POR MENOR EN COMERCIOS DE ALIMENTOS, BEBIDAS O TABACO (SUPERMERCADOS E HIPERMERCADOS)",
  },
  {
    codigo: "471910",
    nombre:
      "VENTA AL POR MENOR EN COMERCIOS DE VESTUARIO Y PRODUCTOS PARA EL HOGAR (GRANDES TIENDAS)",
  },
  {
    codigo: "471990",
    nombre:
      "OTRAS ACTIVIDADES DE VENTA AL POR MENOR EN COMERCIOS NO ESPECIALIZADOS N.C.P.",
  },
  {
    codigo: "472101",
    nombre:
      "VENTA AL POR MENOR DE ALIMENTOS EN COMERCIOS ESPECIALIZADOS (ALMACENES PEQUEÑOS Y MINIMARKET)",
  },
  {
    codigo: "472102",
    nombre:
      "VENTA AL POR MENOR EN COMERCIOS ESPECIALIZADOS DE CARNE Y PRODUCTOS CÁRNICOS",
  },
  {
    codigo: "472103",
    nombre:
      "VENTA AL POR MENOR EN COMERCIOS ESPECIALIZADOS DE FRUTAS Y VERDURAS (VERDULERÍAS)",
  },
  {
    codigo: "472104",
    nombre:
      "VENTA AL POR MENOR EN COMERCIOS ESPECIALIZADOS DE PESCADO, MARISCOS Y PRODUCTOS CONEXOS",
  },
  {
    codigo: "472105",
    nombre:
      "VENTA AL POR MENOR EN COMERCIOS ESPECIALIZADOS DE PRODUCTOS DE PANADERÍA Y PASTELERÍA",
  },
  {
    codigo: "472109",
    nombre:
      "VENTA AL POR MENOR EN COMERCIOS ESPECIALIZADOS DE HUEVOS, CONFITES Y PRODUCTOS ALIMENTICIOS N.C.P.",
  },
  {
    codigo: "472200",
    nombre:
      "VENTA AL POR MENOR DE BEBIDAS ALCOHÓLICAS Y NO ALCOHÓLICAS EN COMERCIOS ESPECIALIZADOS (BOTILLERÍAS)",
  },
  {
    codigo: "472300",
    nombre:
      "VENTA AL POR MENOR DE TABACO Y PRODUCTOS DE TABACO EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "473000",
    nombre:
      "VENTA AL POR MENOR DE COMBUSTIBLES PARA VEHÍCULOS AUTOMOTORES EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "474100",
    nombre:
      "VENTA AL POR MENOR DE COMPUTADORES, EQUIPO PERIFÉRICO, PROGRAMAS INFORMÁTICOS Y EQUIPO DE TELECOM.",
  },
  {
    codigo: "474200",
    nombre:
      "VENTA AL POR MENOR DE EQUIPO DE SONIDO Y DE VIDEO EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "475100",
    nombre:
      "VENTA AL POR MENOR DE TELAS, LANAS, HILOS Y SIMILARES EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "475201",
    nombre:
      "VENTA AL POR MENOR DE ARTÍCULOS DE FERRETERÍA Y MATERIALES DE CONSTRUCCIÓN",
  },
  {
    codigo: "475202",
    nombre:
      "VENTA AL POR MENOR DE PINTURAS, BARNICES Y LACAS EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "475203",
    nombre:
      "VENTA AL POR MENOR DE PRODUCTOS DE VIDRIO EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "475300",
    nombre:
      "VENTA AL POR MENOR DE TAPICES, ALFOMBRAS Y CUBRIMIENTOS PARA PAREDES Y PISOS",
  },
  {
    codigo: "475901",
    nombre:
      "VENTA AL POR MENOR DE MUEBLES Y COLCHONES EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "475902",
    nombre:
      "VENTA AL POR MENOR DE INSTRUMENTOS MUSICALES EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "475909",
    nombre:
      "VENTA AL POR MENOR DE APARATOS ELÉCTRICOS, TEXTILES PARA EL HOGAR Y OTROS ENSERES DOMÉSTICOS N.C.P.",
  },
  {
    codigo: "476101",
    nombre: "VENTA AL POR MENOR DE LIBROS EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "476102",
    nombre:
      "VENTA AL POR MENOR DE DIARIOS Y REVISTAS EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "476103",
    nombre:
      "VENTA AL POR MENOR DE ARTÍCULOS DE PAPELERÍA Y ESCRITORIO EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "476200",
    nombre:
      "VENTA AL POR MENOR DE GRABACIONES DE MÚSICA Y DE VIDEO EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "476301",
    nombre:
      "VENTA AL POR MENOR DE ARTÍCULOS DE CAZA Y PESCA EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "476302",
    nombre:
      "VENTA AL POR MENOR DE BICICLETAS Y SUS REPUESTOS EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "476309",
    nombre: "VENTA AL POR MENOR DE OTROS ARTÍCULOS Y EQUIPOS DE DEPORTE N.C.P.",
  },
  {
    codigo: "476400",
    nombre:
      "VENTA AL POR MENOR DE JUEGOS Y JUGUETES EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "477101",
    nombre: "VENTA AL POR MENOR DE CALZADO EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "477102",
    nombre:
      "VENTA AL POR MENOR DE PRENDAS Y ACCESORIOS DE VESTIR EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "477103",
    nombre:
      "VENTA AL POR MENOR DE CARTERAS, MALETAS Y OTROS ACCESORIOS DE VIAJE EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "477201",
    nombre:
      "VENTA AL POR MENOR DE PRODUCTOS FARMACÉUTICOS Y MEDICINALES EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "477202",
    nombre:
      "VENTA AL POR MENOR DE ARTÍCULOS ORTOPÉDICOS EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "477203",
    nombre:
      "VENTA AL POR MENOR DE ARTÍCULOS DE PERFUMERÍA, DE TOCADOR Y COSMÉTICOS EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "477310",
    nombre:
      "VENTA AL POR MENOR DE GAS LICUADO EN BOMBONAS (CILINDROS) EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "477391",
    nombre:
      "VENTA AL POR MENOR DE ALIMENTO Y ACCESORIOS PARA MASCOTAS EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "477392",
    nombre:
      "VENTA AL POR MENOR DE ARMAS Y MUNICIONES EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "477393",
    nombre:
      "VENTA AL POR MENOR DE ARTÍCULOS ÓPTICOS EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "477394",
    nombre:
      "VENTA AL POR MENOR DE ARTÍCULOS DE JOYERÍA, BISUTERÍA Y RELOJERÍA EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "477395",
    nombre:
      "VENTA AL POR MENOR DE CARBÓN, LEÑA Y OTROS COMBUSTIBLES DE USO DOMÉSTICO EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "477396",
    nombre:
      "VENTA AL POR MENOR DE RECUERDOS, ARTESANÍAS Y ARTÍCULOS RELIGIOSOS EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "477397",
    nombre:
      "VENTA AL POR MENOR DE FLORES, PLANTAS, ARBOLES, SEMILLAS Y ABONOS EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "477398",
    nombre: "VENTA AL POR MENOR DE MASCOTAS EN COMERCIOS ESPECIALIZADOS",
  },
  {
    codigo: "477399",
    nombre:
      "VENTA AL POR MENOR DE OTROS PRODUCTOS EN COMERCIOS ESPECIALIZADOS N.C.P.",
  },
  {
    codigo: "477401",
    nombre: "VENTA AL POR MENOR DE ANTIGÜEDADES EN COMERCIOS",
  },
  { codigo: "477402", nombre: "VENTA AL POR MENOR DE ROPA USADA EN COMERCIOS" },
  {
    codigo: "477409",
    nombre:
      "VENTA AL POR MENOR DE OTROS ARTÍCULOS DE SEGUNDA MANO EN COMERCIOS N.C.P.",
  },
  {
    codigo: "478100",
    nombre:
      "VENTA AL POR MENOR DE ALIMENTOS, BEBIDAS Y TABACO EN PUESTOS DE VENTA Y MERCADOS (INCLUYE FERIAS)",
  },
  {
    codigo: "478200",
    nombre:
      "VENTA AL POR MENOR DE PRODUCTOS TEXTILES, PRENDAS DE VESTIR Y CALZADO EN PUESTOS DE VENTA Y MERCADOS",
  },
  {
    codigo: "478900",
    nombre:
      "VENTA AL POR MENOR DE OTROS PRODUCTOS EN PUESTOS DE VENTA Y MERCADOS (INCLUYE FERIAS)",
  },
  {
    codigo: "479100",
    nombre: "VENTA AL POR MENOR POR CORREO, POR INTERNET Y VÍA TELEFÓNICA",
  },
  {
    codigo: "479901",
    nombre:
      "VENTA AL POR MENOR REALIZADA POR INDEPENDIENTES EN LA LOCOMOCIÓN COLECTIVA (LEY 20.388)",
  },
  {
    codigo: "479902",
    nombre: "VENTA AL POR MENOR MEDIANTE MAQUINAS EXPENDEDORAS",
  },
  {
    codigo: "479903",
    nombre:
      "VENTA AL POR MENOR POR COMISIONISTAS (NO DEPENDIENTES DE COMERCIOS)",
  },
  {
    codigo: "479909",
    nombre:
      "OTRAS ACTIVIDADES DE VENTA POR MENOR NO REALIZADAS EN COMERCIOS, PUESTOS DE VENTA O MERCADOS N.C.P.",
  },

  // TRANSPORTE Y ALMACENAMIENTO
  {
    codigo: "491100",
    nombre: "TRANSPORTE INTERURBANO DE PASAJEROS POR FERROCARRIL",
  },
  { codigo: "491200", nombre: "TRANSPORTE DE CARGA POR FERROCARRIL" },
  {
    codigo: "492110",
    nombre: "TRANSPORTE URBANO Y SUBURBANO DE PASAJEROS VÍA METRO Y METROTREN",
  },
  {
    codigo: "492120",
    nombre:
      "TRANSPORTE URBANO Y SUBURBANO DE PASAJEROS VÍA LOCOMOCIÓN COLECTIVA",
  },
  { codigo: "492130", nombre: "TRANSPORTE DE PASAJEROS VÍA TAXI COLECTIVO" },
  {
    codigo: "492190",
    nombre:
      "OTRAS ACTIVIDADES DE TRANSPORTE URBANO Y SUBURBANO DE PASAJEROS POR VÍA TERRESTRE N.C.P.",
  },
  { codigo: "492210", nombre: "SERVICIOS DE TRANSPORTE DE ESCOLARES" },
  { codigo: "492220", nombre: "SERVICIOS DE TRANSPORTE DE TRABAJADORES" },
  {
    codigo: "492230",
    nombre: "SERVICIOS DE TRANSPORTE DE PASAJEROS EN TAXIS LIBRES Y RADIOTAXIS",
  },
  { codigo: "492240", nombre: "SERVICIOS DE TRANSPORTE A TURISTAS" },
  { codigo: "492250", nombre: "TRANSPORTE DE PASAJEROS EN BUSES INTERURBANOS" },
  {
    codigo: "492290",
    nombre:
      "OTRAS ACTIVIDADES DE TRANSPORTE DE PASAJEROS POR VÍA TERRESTRE N.C.P.",
  },
  { codigo: "492300", nombre: "TRANSPORTE DE CARGA POR CARRETERA" },
  { codigo: "493010", nombre: "TRANSPORTE POR OLEODUCTOS" },
  { codigo: "493020", nombre: "TRANSPORTE POR GASODUCTOS" },
  {
    codigo: "493090",
    nombre: "OTRAS ACTIVIDADES DE TRANSPORTE POR TUBERÍAS N.C.P.",
  },
  {
    codigo: "501100",
    nombre: "TRANSPORTE DE PASAJEROS MARÍTIMO Y DE CABOTAJE",
  },
  { codigo: "501200", nombre: "TRANSPORTE DE CARGA MARÍTIMO Y DE CABOTAJE" },
  {
    codigo: "502100",
    nombre: "TRANSPORTE DE PASAJEROS POR VÍAS DE NAVEGACIÓN INTERIORES",
  },
  {
    codigo: "502200",
    nombre: "TRANSPORTE DE CARGA POR VÍAS DE NAVEGACIÓN INTERIORES",
  },
  { codigo: "511000", nombre: "TRANSPORTE DE PASAJEROS POR VÍA AÉREA" },
  { codigo: "512000", nombre: "TRANSPORTE DE CARGA POR VÍA AÉREA" },
  {
    codigo: "521001",
    nombre: "EXPLOTACIÓN DE FRIGORÍFICOS PARA ALMACENAMIENTO Y DEPÓSITO",
  },
  {
    codigo: "521009",
    nombre: "OTROS SERVICIOS DE ALMACENAMIENTO Y DEPÓSITO N.C.P.",
  },
  {
    codigo: "522110",
    nombre: "EXPLOTACIÓN DE TERMINALES TERRESTRES DE PASAJEROS",
  },
  {
    codigo: "522120",
    nombre:
      "EXPLOTACIÓN DE ESTACIONAMIENTOS DE VEHÍCULOS AUTOMOTORES Y PARQUÍMETROS",
  },
  {
    codigo: "522130",
    nombre: "SERVICIOS PRESTADOS POR CONCESIONARIOS DE CARRETERAS",
  },
  {
    codigo: "522190",
    nombre:
      "ACTIVIDADES DE SERVICIOS VINCULADAS AL TRANSPORTE TERRESTRE N.C.P.",
  },
  {
    codigo: "522200",
    nombre: "ACTIVIDADES DE SERVICIOS VINCULADAS AL TRANSPORTE ACUÁTICO",
  },
  {
    codigo: "522300",
    nombre: "ACTIVIDADES DE SERVICIOS VINCULADAS AL TRANSPORTE AÉREO",
  },
  { codigo: "522400", nombre: "MANIPULACIÓN DE LA CARGA" },
  { codigo: "522910", nombre: "AGENCIAS DE ADUANAS" },
  { codigo: "522920", nombre: "AGENCIAS DE NAVES" },
  {
    codigo: "522990",
    nombre: "OTRAS ACTIVIDADES DE APOYO AL TRANSPORTE N.C.P.",
  },
  { codigo: "531000", nombre: "ACTIVIDADES POSTALES" },
  { codigo: "532000", nombre: "ACTIVIDADES DE MENSAJERÍA" },

  // ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS
  { codigo: "551001", nombre: "ACTIVIDADES DE HOTELES" },
  { codigo: "551002", nombre: "ACTIVIDADES DE MOTELES" },
  { codigo: "551003", nombre: "ACTIVIDADES DE RESIDENCIALES PARA TURISTAS" },
  {
    codigo: "551009",
    nombre: "OTRAS ACTIVIDADES DE ALOJAMIENTO PARA TURISTAS N.C.P.",
  },
  {
    codigo: "552000",
    nombre: "ACTIVIDADES DE CAMPING Y DE PARQUES PARA CASAS RODANTES",
  },
  {
    codigo: "559001",
    nombre: "ACTIVIDADES DE RESIDENCIALES PARA ESTUDIANTES Y TRABAJADORES",
  },
  { codigo: "559009", nombre: "OTRAS ACTIVIDADES DE ALOJAMIENTO N.C.P." },
  {
    codigo: "561000",
    nombre: "ACTIVIDADES DE RESTAURANTES Y DE SERVICIO MÓVIL DE COMIDAS",
  },
  {
    codigo: "562100",
    nombre: "SUMINISTRO DE COMIDAS POR ENCARGO (SERVICIOS DE BANQUETERÍA)",
  },
  {
    codigo: "562900",
    nombre:
      "SUMINISTRO INDUSTRIAL DE COMIDAS POR ENCARGO; CONCESIÓN DE SERVICIOS DE ALIMENTACIÓN",
  },
  {
    codigo: "563001",
    nombre:
      "ACTIVIDADES DE DISCOTECAS Y CABARET (NIGHT CLUB), CON PREDOMINIO DEL SERVICIO DE BEBIDAS",
  },
  {
    codigo: "563009",
    nombre: "OTRAS ACTIVIDADES DE SERVICIO DE BEBIDAS N.C.P.",
  },

  // INFORMACIÓN Y COMUNICACIONES
  { codigo: "581100", nombre: "EDICIÓN DE LIBROS" },
  { codigo: "581200", nombre: "EDICIÓN DE DIRECTORIOS Y LISTAS DE CORREO" },
  {
    codigo: "581300",
    nombre: "EDICIÓN DE DIARIOS, REVISTAS Y OTRAS PUBLICACIONES PERIÓDICAS",
  },
  { codigo: "581900", nombre: "OTRAS ACTIVIDADES DE EDICIÓN" },
  { codigo: "582000", nombre: "EDICIÓN DE PROGRAMAS INFORMÁTICOS" },
  {
    codigo: "591100",
    nombre:
      "ACTIVIDADES DE PRODUCCIÓN DE PELÍCULAS CINEMATOGRÁFICAS, VIDEOS Y PROGRAMAS DE TELEVISIÓN",
  },
  {
    codigo: "591200",
    nombre:
      "ACTIVIDADES DE POSTPRODUCCIÓN DE PELÍCULAS CINEMATOGRÁFICAS, VIDEOS Y PROGRAMAS DE TELEVISIÓN",
  },
  {
    codigo: "591300",
    nombre:
      "ACTIVIDADES DE DISTRIBUCIÓN DE PELÍCULAS CINEMATOGRÁFICAS, VIDEOS Y PROGRAMAS DE TELEVISIÓN",
  },
  {
    codigo: "591400",
    nombre:
      "ACTIVIDADES DE EXHIBICIÓN DE PELÍCULAS CINEMATOGRÁFICAS Y CINTAS DE VIDEO",
  },
  {
    codigo: "592000",
    nombre: "ACTIVIDADES DE GRABACIÓN DE SONIDO Y EDICIÓN DE MÚSICA",
  },
  { codigo: "601000", nombre: "TRANSMISIONES DE RADIO" },
  { codigo: "602000", nombre: "PROGRAMACIÓN Y TRANSMISIONES DE TELEVISIÓN" },
  { codigo: "611010", nombre: "TELEFONÍA FIJA" },
  { codigo: "611020", nombre: "TELEFONÍA LARGA DISTANCIA" },
  { codigo: "611030", nombre: "TELEVISIÓN DE PAGO POR CABLE" },
  {
    codigo: "611090",
    nombre: "OTROS SERVICIOS DE TELECOMUNICACIONES ALÁMBRICAS N.C.P.",
  },
  { codigo: "612010", nombre: "TELEFONÍA MÓVIL CELULAR" },
  { codigo: "612020", nombre: "RADIOCOMUNICACIONES MÓVILES" },
  { codigo: "612030", nombre: "TELEVISIÓN DE PAGO INALÁMBRICA" },
  {
    codigo: "612090",
    nombre: "OTROS SERVICIOS DE TELECOMUNICACIONES INALÁMBRICAS N.C.P.",
  },
  { codigo: "613010", nombre: "TELEFONÍA MÓVIL SATELITAL" },
  { codigo: "613020", nombre: "TELEVISIÓN DE PAGO SATELITAL" },
  {
    codigo: "613090",
    nombre: "OTROS SERVICIOS DE TELECOMUNICACIONES POR SATÉLITE N.C.P.",
  },
  {
    codigo: "619010",
    nombre: "CENTROS DE LLAMADOS Y CENTROS DE ACCESO A INTERNET",
  },
  {
    codigo: "619090",
    nombre: "OTRAS ACTIVIDADES DE TELECOMUNICACIONES N.C.P.",
  },
  { codigo: "620100", nombre: "ACTIVIDADES DE PROGRAMACIÓN INFORMÁTICA" },
  {
    codigo: "620200",
    nombre:
      "ACTIVIDADES DE CONSULTORÍA DE INFORMÁTICA Y DE GESTIÓN DE INSTALACIONES INFORMÁTICAS",
  },
  {
    codigo: "620900",
    nombre:
      "OTRAS ACTIVIDADES DE TECNOLOGÍA DE LA INFORMACIÓN Y DE SERVICIOS INFORMÁTICOS",
  },
  {
    codigo: "631100",
    nombre: "PROCESAMIENTO DE DATOS, HOSPEDAJE Y ACTIVIDADES CONEXAS",
  },
  { codigo: "631200", nombre: "PORTALES WEB" },
  { codigo: "639100", nombre: "ACTIVIDADES DE AGENCIAS DE NOTICIAS" },
  {
    codigo: "639900",
    nombre: "OTRAS ACTIVIDADES DE SERVICIOS DE INFORMACIÓN N.C.P.",
  },

  // ACTIVIDADES FINANCIERAS Y DE SEGUROS
  { codigo: "641100", nombre: "BANCA CENTRAL" },
  { codigo: "641910", nombre: "ACTIVIDADES BANCARIAS" },
  {
    codigo: "641990",
    nombre: "OTROS TIPOS DE INTERMEDIACIÓN MONETARIA N.C.P.",
  },
  { codigo: "642000", nombre: "ACTIVIDADES DE SOCIEDADES DE CARTERA" },
  {
    codigo: "643000",
    nombre:
      "FONDOS Y SOCIEDADES DE INVERSIÓN Y ENTIDADES FINANCIERAS SIMILARES",
  },
  { codigo: "649100", nombre: "LEASING FINANCIERO" },
  { codigo: "649201", nombre: "FINANCIERAS" },
  { codigo: "649202", nombre: "ACTIVIDADES DE CRÉDITO PRENDARIO" },
  { codigo: "649203", nombre: "CAJAS DE COMPENSACIÓN" },
  {
    codigo: "649209",
    nombre: "OTRAS ACTIVIDADES DE CONCESIÓN DE CRÉDITO N.C.P.",
  },
  {
    codigo: "649900",
    nombre:
      "OTRAS ACTIVIDADES DE SERVICIOS FINANCIEROS, EXCEPTO LAS DE SEGUROS Y FONDOS DE PENSIONES N.C.P.",
  },
  { codigo: "651100", nombre: "SEGUROS DE VIDA" },
  {
    codigo: "651210",
    nombre: "SEGUROS GENERALES, EXCEPTO ACTIVIDADES DE ISAPRES",
  },
  { codigo: "651220", nombre: "ACTIVIDADES DE ISAPRES" },
  { codigo: "652000", nombre: "REASEGUROS" },
  { codigo: "653000", nombre: "FONDOS DE PENSIONES" },
  { codigo: "661100", nombre: "ADMINISTRACIÓN DE MERCADOS FINANCIEROS" },
  { codigo: "661201", nombre: "ACTIVIDADES DE SECURITIZADORAS" },
  { codigo: "661202", nombre: "CORREDORES DE BOLSA" },
  { codigo: "661203", nombre: "AGENTES DE VALORES" },
  {
    codigo: "661204",
    nombre: "ACTIVIDADES DE CASAS DE CAMBIO Y OPERADORES DE DIVISA",
  },
  {
    codigo: "661209",
    nombre: "OTROS SERVICIOS DE CORRETAJE DE VALORES Y COMMODITIES N.C.P.",
  },
  { codigo: "661901", nombre: "ACTIVIDADES DE CÁMARAS DE COMPENSACIÓN" },
  { codigo: "661902", nombre: "ADMINISTRACIÓN DE TARJETAS DE CRÉDITO" },
  {
    codigo: "661903",
    nombre:
      "EMPRESAS DE ASESORÍA Y CONSULTORÍA EN INVERSIÓN FINANCIERA; SOCIEDADES DE APOYO AL GIRO",
  },
  { codigo: "661904", nombre: "ACTIVIDADES DE CLASIFICADORAS DE RIESGO" },
  {
    codigo: "661909",
    nombre:
      "OTRAS ACTIVIDADES AUXILIARES DE LAS ACTIVIDADES DE SERVICIOS FINANCIEROS N.C.P.",
  },
  {
    codigo: "662100",
    nombre:
      "EVALUACIÓN DE RIESGOS Y DAÑOS (INCLUYE ACTIVIDADES DE LIQUIDADORES DE SEGUROS)",
  },
  {
    codigo: "662200",
    nombre: "ACTIVIDADES DE AGENTES Y CORREDORES DE SEGUROS",
  },
  {
    codigo: "662900",
    nombre:
      "OTRAS ACTIVIDADES AUXILIARES DE LAS ACTIVIDADES DE SEGUROS Y FONDOS DE PENSIONES",
  },
  { codigo: "663010", nombre: "ADMINISTRADORAS DE FONDOS DE PENSIONES (AFP)" },
  { codigo: "663091", nombre: "ADMINISTRADORAS DE FONDOS DE INVERSIÓN" },
  { codigo: "663092", nombre: "ADMINISTRADORAS DE FONDOS MUTUOS" },
  {
    codigo: "663093",
    nombre:
      "ADMINISTRADORAS DE FICES (FONDOS DE INVERSIÓN DE CAPITAL EXTRANJERO)",
  },
  { codigo: "663094", nombre: "ADMINISTRADORAS DE FONDOS PARA LA VIVIENDA" },
  {
    codigo: "663099",
    nombre: "ADMINISTRADORAS DE FONDOS PARA OTROS FINES N.C.P.",
  },

  // ACTIVIDADES INMOBILIARIAS
  {
    codigo: "681011",
    nombre:
      "ALQUILER DE BIENES INMUEBLES AMOBLADOS O CON EQUIPOS Y MAQUINARIAS",
  },
  {
    codigo: "681012",
    nombre: "COMPRA, VENTA Y ALQUILER (EXCEPTO AMOBLADOS) DE INMUEBLES",
  },
  { codigo: "681020", nombre: "SERVICIOS IMPUTADOS DE ALQUILER DE VIVIENDAS" },
  {
    codigo: "682000",
    nombre:
      "ACTIVIDADES INMOBILIARIAS REALIZADAS A CAMBIO DE UNA RETRIBUCIÓN O POR CONTRATA",
  },

  // ACTIVIDADES PROFESIONALES, CIENTIFICAS Y TÉCNICAS
  {
    codigo: "691001",
    nombre: "SERVICIOS DE ASESORAMIENTO Y REPRESENTACIÓN JURÍDICA",
  },
  { codigo: "691002", nombre: "SERVICIO NOTARIAL" },
  { codigo: "691003", nombre: "CONSERVADOR DE BIENES RAÍCES" },
  { codigo: "691004", nombre: "RECEPTORES JUDICIALES" },
  {
    codigo: "691009",
    nombre:
      "SERVICIOS DE ARBITRAJE; SÍNDICOS DE QUIEBRA Y PERITOS JUDICIALES; OTRAS ACTIVIDADES JURÍDICAS N.C.P.",
  },
  {
    codigo: "692000",
    nombre:
      "ACTIVIDADES DE CONTABILIDAD, TENEDURÍA DE LIBROS Y AUDITORÍA; CONSULTORÍA FISCAL",
  },
  { codigo: "701000", nombre: "ACTIVIDADES DE OFICINAS PRINCIPALES" },
  { codigo: "702000", nombre: "ACTIVIDADES DE CONSULTORÍA DE GESTIÓN" },
  {
    codigo: "711001",
    nombre:
      "SERVICIOS DE ARQUITECTURA (DISEÑO DE EDIFICIOS, DIBUJO DE PLANOS DE CONSTRUCCIÓN, ENTRE OTROS)",
  },
  {
    codigo: "711002",
    nombre:
      "EMPRESAS DE SERVICIOS DE INGENIERÍA Y ACTIVIDADES CONEXAS DE CONSULTORÍA TÉCNICA",
  },
  {
    codigo: "711003",
    nombre:
      "SERVICIOS PROFESIONALES DE INGENIERÍA Y ACTIVIDADES CONEXAS DE CONSULTORÍA TÉCNICA",
  },
  {
    codigo: "712001",
    nombre:
      "ACTIVIDADES DE PLANTAS DE REVISIÓN TÉCNICA PARA VEHÍCULOS AUTOMOTORES",
  },
  {
    codigo: "712009",
    nombre:
      "OTROS SERVICIOS DE ENSAYOS Y ANÁLISIS TÉCNICOS (EXCEPTO ACTIVIDADES DE PLANTAS DE REVISIÓN TÉCNICA)",
  },
  {
    codigo: "721000",
    nombre:
      "INVESTIGACIONES Y DESARROLLO EXPERIMENTAL EN EL CAMPO DE LAS CIENCIAS NATURALES Y LA INGENIERÍA",
  },
  {
    codigo: "722000",
    nombre:
      "INVESTIGACIONES Y DESARROLLO EXPERIMENTAL EN EL CAMPO DE LAS CIENCIAS SOCIALES Y LAS HUMANIDADES",
  },
  {
    codigo: "731001",
    nombre: "SERVICIOS DE PUBLICIDAD PRESTADOS POR EMPRESAS",
  },
  {
    codigo: "731002",
    nombre: "SERVICIOS DE PUBLICIDAD PRESTADOS POR PROFESIONALES",
  },
  {
    codigo: "732000",
    nombre: "ESTUDIOS DE MERCADO Y ENCUESTAS DE OPINIÓN PÚBLICA",
  },
  { codigo: "741001", nombre: "ACTIVIDADES DE DISEÑO DE VESTUARIO" },
  {
    codigo: "741002",
    nombre: "ACTIVIDADES DE DISEÑO Y DECORACIÓN DE INTERIORES",
  },
  {
    codigo: "741009",
    nombre: "OTRAS ACTIVIDADES ESPECIALIZADAS DE DISEÑO N.C.P.",
  },
  {
    codigo: "742001",
    nombre: "SERVICIOS DE REVELADO, IMPRESIÓN Y AMPLIACIÓN DE FOTOGRAFÍAS",
  },
  { codigo: "742002", nombre: "SERVICIOS Y ACTIVIDADES DE FOTOGRAFÍA" },
  { codigo: "742003", nombre: "SERVICIOS PERSONALES DE FOTOGRAFÍA" },
  {
    codigo: "749001",
    nombre:
      "ASESORÍA Y GESTIÓN EN LA COMPRA O VENTA DE PEQUEÑAS Y MEDIANAS EMPRESAS",
  },
  {
    codigo: "749002",
    nombre: "SERVICIOS DE TRADUCCIÓN E INTERPRETACIÓN PRESTADOS POR EMPRESAS",
  },
  {
    codigo: "749003",
    nombre: "SERVICIOS PERSONALES DE TRADUCCIÓN E INTERPRETACIÓN",
  },
  {
    codigo: "749004",
    nombre:
      "ACTIVIDADES DE AGENCIAS Y AGENTES DE REPRESENTACIÓN DE ACTORES, DEPORTISTAS Y OTRAS FIGURAS PÚBLICAS",
  },
  {
    codigo: "749009",
    nombre: "OTRAS ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS N.C.P.",
  },
  { codigo: "750000", nombre: "ACTIVIDADES VETERINARIAS" },

  // Continúa con más sectores...
  { codigo: "771000", nombre: "ALQUILER DE VEHÍCULOS AUTOMOTORES" },
  {
    codigo: "772000",
    nombre: "ALQUILER DE EFECTOS PERSONALES Y ENSERES DOMÉSTICOS",
  },
  {
    codigo: "773000",
    nombre: "ALQUILER DE OTROS TIPOS DE MAQUINARIA, EQUIPO Y BIENES TANGIBLES",
  },
  {
    codigo: "774000",
    nombre:
      "ARRENDAMIENTO DE PROPIEDAD INTELECTUAL Y PRODUCTOS SIMILARES, EXCEPTO OBRAS PROTEGIDAS POR DERECHOS DE AUTOR",
  },
  { codigo: "781000", nombre: "ACTIVIDADES DE AGENCIAS DE EMPLEO" },
  { codigo: "782000", nombre: "ACTIVIDADES DE AGENCIAS DE EMPLEO TEMPORAL" },
  {
    codigo: "783000",
    nombre: "OTRAS ACTIVIDADES DE DOTACIÓN DE RECURSOS HUMANOS",
  },
  { codigo: "791100", nombre: "ACTIVIDADES DE AGENCIAS DE VIAJES" },
  { codigo: "791200", nombre: "ACTIVIDADES DE OPERADORES TURÍSTICOS" },
  {
    codigo: "799000",
    nombre: "OTROS SERVICIOS DE RESERVAS Y ACTIVIDADES CONEXAS",
  },
  { codigo: "801000", nombre: "ACTIVIDADES DE SEGURIDAD PRIVADA" },
  {
    codigo: "802000",
    nombre: "ACTIVIDADES DE SERVICIOS DE SISTEMAS DE SEGURIDAD",
  },
  { codigo: "803000", nombre: "ACTIVIDADES DE INVESTIGACIÓN" },
  {
    codigo: "811000",
    nombre: "ACTIVIDADES COMBINADAS DE APOYO A INSTALACIONES",
  },
  { codigo: "812100", nombre: "LIMPIEZA GENERAL DE EDIFICIOS" },
  {
    codigo: "812900",
    nombre:
      "OTRAS ACTIVIDADES DE LIMPIEZA DE EDIFICIOS E INSTALACIONES INDUSTRIALES",
  },
  {
    codigo: "813000",
    nombre: "ACTIVIDADES DE PAISAJISMO Y SERVICIOS DE MANTENIMIENTO CONEXOS",
  },
  {
    codigo: "821100",
    nombre: "ACTIVIDADES ADMINISTRATIVAS Y DE APOYO DE OFICINA",
  },
  {
    codigo: "821900",
    nombre:
      "FOTOCOPIADO, PREPARACIÓN DE DOCUMENTOS Y OTRAS ACTIVIDADES ESPECIALIZADAS DE APOYO DE OFICINA",
  },
  { codigo: "822000", nombre: "ACTIVIDADES DE CALL CENTER" },
  {
    codigo: "823000",
    nombre: "ORGANIZACIÓN DE CONVENCIONES Y EXPOSICIONES COMERCIALES",
  },
  {
    codigo: "829100",
    nombre:
      "ACTIVIDADES DE AGENCIAS DE COBRO Y AGENCIAS DE CALIFICACIÓN CREDITICIA",
  },
  { codigo: "829200", nombre: "ACTIVIDADES DE ENVASADO Y EMPAQUETADO" },
  {
    codigo: "829900",
    nombre: "OTRAS ACTIVIDADES DE SERVICIOS DE APOYO A LAS EMPRESAS N.C.P.",
  },
  {
    codigo: "841100",
    nombre: "ACTIVIDADES DE LA ADMINISTRACIÓN PÚBLICA EN GENERAL",
  },
  {
    codigo: "841200",
    nombre:
      "REGULACIÓN DE LAS ACTIVIDADES DE ORGANISMOS QUE PRESTAN SERVICIOS DE SALUD, EDUCATIVOS, CULTURALES Y OTROS SERVICIOS SOCIALES, EXCEPTO SERVICIOS DE SEGURIDAD SOCIAL",
  },
  {
    codigo: "841300",
    nombre: "REGULACIÓN Y FACILITACIÓN DE LA ACTIVIDAD ECONÓMICA",
  },
  { codigo: "842100", nombre: "RELACIONES EXTERIORES" },
  { codigo: "842200", nombre: "ACTIVIDADES DE DEFENSA" },
  {
    codigo: "842300",
    nombre: "ACTIVIDADES DE MANTENIMIENTO DEL ORDEN PÚBLICO Y DE SEGURIDAD",
  },
  {
    codigo: "843000",
    nombre:
      "ACTIVIDADES DE PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA",
  },
  { codigo: "851000", nombre: "ENSEÑANZA PREESCOLAR" },
  { codigo: "852100", nombre: "ENSEÑANZA PRIMARIA" },
  { codigo: "852200", nombre: "ENSEÑANZA SECUNDARIA DE FORMACIÓN GENERAL" },
  {
    codigo: "852300",
    nombre: "ENSEÑANZA SECUNDARIA DE FORMACIÓN TÉCNICA Y PROFESIONAL",
  },
  { codigo: "853100", nombre: "ENSEÑANZA UNIVERSITARIA" },
  {
    codigo: "853200",
    nombre: "ENSEÑANZA TÉCNICO PROFESIONAL (CARRERAS DE 4 A 5 SEMESTRES)",
  },
  {
    codigo: "853300",
    nombre: "ENSEÑANZA PROFESIONAL (CARRERAS DE 6 A 12 SEMESTRES)",
  },
  { codigo: "854100", nombre: "ENSEÑANZA DEPORTIVA Y RECREATIVA" },
  { codigo: "854200", nombre: "ENSEÑANZA CULTURAL" },
  { codigo: "854900", nombre: "OTROS TIPOS DE ENSEÑANZA N.C.P." },
  { codigo: "855000", nombre: "ACTIVIDADES DE APOYO A LA ENSEÑANZA" },
  { codigo: "861000", nombre: "ACTIVIDADES DE HOSPITALES Y CLÍNICAS" },
  { codigo: "862100", nombre: "ACTIVIDADES DE MÉDICOS GENERALES" },
  { codigo: "862200", nombre: "ACTIVIDADES DE MÉDICOS ESPECIALISTAS" },
  { codigo: "862300", nombre: "ACTIVIDADES ODONTOLÓGICAS" },
  { codigo: "869001", nombre: "ACTIVIDADES DE KINESIOLOGÍA" },
  { codigo: "869002", nombre: "ACTIVIDADES DE ENFERMERÍA" },
  { codigo: "869003", nombre: "ACTIVIDADES DE OBSTETRICIA Y PARTERAS" },
  {
    codigo: "869004",
    nombre: "ACTIVIDADES DE LABORATORIOS CLÍNICOS Y BANCOS DE SANGRE",
  },
  {
    codigo: "869005",
    nombre: "ACTIVIDADES DE DIAGNÓSTICO PRESTADAS POR EMPRESAS",
  },
  {
    codigo: "869006",
    nombre: "ACTIVIDADES DE DIAGNÓSTICO PRESTADAS POR PROFESIONALES",
  },
  {
    codigo: "869007",
    nombre: "ACTIVIDADES DE OTROS PROFESIONALES DE LA SALUD",
  },
  {
    codigo: "869009",
    nombre: "OTRAS ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA N.C.P.",
  },
  {
    codigo: "871000",
    nombre: "ACTIVIDADES DE ATENCIÓN DE ENFERMERÍA EN INSTITUCIONES",
  },
  {
    codigo: "872000",
    nombre:
      "ACTIVIDADES DE ATENCIÓN EN INSTITUCIONES PARA PERSONAS CON RETRASO MENTAL, ENFERMOS MENTALES Y TOXICÓMANOS",
  },
  {
    codigo: "873000",
    nombre:
      "ACTIVIDADES DE ATENCIÓN EN INSTITUCIONES PARA PERSONAS DE EDAD Y PERSONAS CON DISCAPACIDAD",
  },
  {
    codigo: "879000",
    nombre: "OTRAS ACTIVIDADES DE ATENCIÓN EN INSTITUCIONES",
  },
  {
    codigo: "881000",
    nombre:
      "ACTIVIDADES DE ASISTENCIA SOCIAL SIN ALOJAMIENTO PARA PERSONAS DE EDAD Y PERSONAS CON DISCAPACIDAD",
  },
  {
    codigo: "889000",
    nombre: "OTRAS ACTIVIDADES DE ASISTENCIA SOCIAL SIN ALOJAMIENTO",
  },
  {
    codigo: "900001",
    nombre:
      "CREACIÓN E INTERPRETACIÓN DE OBRAS DE TEATRO, CONCIERTOS, ESPECTÁCULOS DE DANZA, OTRAS PRODUCCIONES ESCÉNICAS, CIRCENSES Y SIMILARES",
  },
  {
    codigo: "900002",
    nombre: "ACTIVIDADES ARTÍSTICAS Y LITERARIAS REALIZADAS POR EMPRESAS",
  },
  {
    codigo: "900003",
    nombre: "ACTIVIDADES ARTÍSTICAS Y LITERARIAS REALIZADAS POR PROFESIONALES",
  },
  {
    codigo: "900004",
    nombre: "EXPLOTACIÓN DE SALAS DE ESPECTÁCULOS Y ACTIVIDADES CONEXAS",
  },
  { codigo: "910100", nombre: "ACTIVIDADES DE BIBLIOTECAS Y ARCHIVOS" },
  {
    codigo: "910200",
    nombre: "ACTIVIDADES DE MUSEOS Y GESTIÓN DE LUGARES Y EDIFICIOS HISTÓRICOS",
  },
  {
    codigo: "910300",
    nombre:
      "ACTIVIDADES DE JARDINES BOTÁNICOS Y ZOOLÓGICOS Y DE RESERVAS NATURALES",
  },
  { codigo: "920000", nombre: "ACTIVIDADES DE JUEGOS DE AZAR Y APUESTAS" },
  { codigo: "931101", nombre: "GESTIÓN DE INSTALACIONES DEPORTIVAS" },
  { codigo: "931102", nombre: "ACTIVIDADES DE CLUBES DE DEPORTES" },
  { codigo: "931201", nombre: "ACTIVIDADES DE CLUBES PROFESIONALES DE FÚTBOL" },
  { codigo: "931202", nombre: "ACTIVIDADES DE CUADRERAS" },
  {
    codigo: "931203",
    nombre: "PROMOCIÓN Y ORGANIZACIÓN DE COMPETENCIAS DEPORTIVAS",
  },
  { codigo: "931209", nombre: "OTRAS ACTIVIDADES DEPORTIVAS N.C.P." },
  {
    codigo: "932100",
    nombre: "ACTIVIDADES DE PARQUES DE ATRACCIONES Y PARQUES TEMÁTICOS",
  },
  {
    codigo: "932901",
    nombre:
      "ACTIVIDADES DE DISCOTECAS Y CABARET (NIGHT CLUB), CON PREDOMINIO DEL ESPECTÁCULO EN VIVO",
  },
  { codigo: "932902", nombre: "ACTIVIDADES DE SALAS DE BILLAR Y POOL" },
  { codigo: "932903", nombre: "ACTIVIDADES DE JUEGOS ELECTRÓNICOS" },
  {
    codigo: "932909",
    nombre: "OTRAS ACTIVIDADES DE ESPARCIMIENTO Y RECREATIVAS N.C.P.",
  },
  {
    codigo: "941100",
    nombre: "ACTIVIDADES DE ASOCIACIONES EMPRESARIALES Y DE EMPLEADORES",
  },
  { codigo: "941200", nombre: "ACTIVIDADES DE ASOCIACIONES PROFESIONALES" },
  { codigo: "942000", nombre: "ACTIVIDADES DE SINDICATOS" },
  { codigo: "949100", nombre: "ACTIVIDADES DE ORGANIZACIONES RELIGIOSAS" },
  { codigo: "949200", nombre: "ACTIVIDADES DE ORGANIZACIONES POLÍTICAS" },
  { codigo: "949900", nombre: "ACTIVIDADES DE OTRAS ASOCIACIONES N.C.P." },
  {
    codigo: "951100",
    nombre: "REPARACIÓN DE COMPUTADORES Y EQUIPO PERIFÉRICO",
  },
  { codigo: "951200", nombre: "REPARACIÓN DE EQUIPO DE COMUNICACIONES" },
  {
    codigo: "952100",
    nombre: "REPARACIÓN DE APARATOS ELECTRÓNICOS DE CONSUMO",
  },
  {
    codigo: "952200",
    nombre:
      "REPARACIÓN DE APARATOS DE USO DOMÉSTICO Y EQUIPO DOMÉSTICO Y DE JARDINERÍA",
  },
  { codigo: "952300", nombre: "REPARACIÓN DE CALZADO Y ARTÍCULOS DE CUERO" },
  { codigo: "952400", nombre: "REPARACIÓN DE MUEBLES Y ACCESORIOS DOMÉSTICOS" },
  {
    codigo: "952900",
    nombre: "REPARACIÓN DE OTROS EFECTOS PERSONALES Y ENSERES DOMÉSTICOS",
  },
  {
    codigo: "960100",
    nombre:
      "LAVADO Y LIMPIEZA, INCLUIDA LA LIMPIEZA EN SECO, DE PRODUCTOS TEXTILES Y DE PIEL",
  },
  { codigo: "960200", nombre: "PELUQUERÍA Y OTROS TRATAMIENTOS DE BELLEZA" },
  { codigo: "960300", nombre: "POMPAS FÚNEBRES Y ACTIVIDADES CONEXAS" },
  {
    codigo: "960901",
    nombre: "ACTIVIDADES DE BAÑOS TURCOS, SAUNAS Y BAÑOS DE VAPOR",
  },
  { codigo: "960902", nombre: "ACTIVIDADES DE CASAS DE MASAJES" },
  {
    codigo: "960903",
    nombre: "SERVICIOS DE CUIDADO Y MANTENIMIENTO CORPORAL N.C.P.",
  },
  {
    codigo: "960904",
    nombre: "ACTIVIDADES DE TATUAJES Y PERFORACIONES CORPORALES (PIERCING)",
  },
  {
    codigo: "960909",
    nombre: "OTRAS ACTIVIDADES DE SERVICIOS PERSONALES N.C.P.",
  },
  {
    codigo: "970000",
    nombre: "ACTIVIDADES DE LOS HOGARES COMO EMPLEADORES DE PERSONAL DOMÉSTICO",
  },
  {
    codigo: "981000",
    nombre:
      "ACTIVIDADES INDIFERENCIADAS DE LOS HOGARES COMO PRODUCTORES DE BIENES PARA USO PROPIO",
  },
  {
    codigo: "982000",
    nombre:
      "ACTIVIDADES INDIFERENCIADAS DE LOS HOGARES COMO PRODUCTORES DE SERVICIOS PARA USO PROPIO",
  },
  {
    codigo: "990000",
    nombre: "ACTIVIDADES DE ORGANIZACIONES Y ÓRGANOS EXTRATERRITORIALES",
  },
];

export default girosSII;
